# Generated by Django 3.2.4 on 2021-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
