# Generated by Django 3.2.4 on 2021-07-05 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Выполнен')], default='NEW')),
                ('order_sum', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updating_date', models.DateField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.order2')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order2',
            name='positions',
            field=models.ManyToManyField(related_name='orders2', through='MyShop.OrderPosition2', to='MyShop.Product'),
        ),
    ]
