# Generated by Django 3.2.4 on 2021-06-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='updating_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updating_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updating_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='updating_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
