# Generated by Django 3.2.4 on 2021-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_alter_collection_updating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updating_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='updating_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='updating_date',
            field=models.DateField(default=None),
        ),
    ]
