# Generated by Django 3.2.4 on 2021-07-12 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_alter_order_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', to='MyShop.Product'),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
